//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace odev3.Kaynaklar {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class dili {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal dili() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("odev3.Kaynaklar.dili", typeof(dili).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Tümü için geçerli iş parçacığının CurrentUICulture özelliğini geçersiz kular
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   EV benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string anasayfa {
            get {
                return ResourceManager.GetString("anasayfa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EFSANELER benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string efsaneler {
            get {
                return ResourceManager.GetString("efsaneler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bu sitenin tüm hakları Havvanur Bozkurt&apos;a aittir. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string footer {
            get {
                return ResourceManager.GetString("footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MARDİN HAKKINDA GENEL BİLGİ benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string genel_baslik {
            get {
                return ResourceManager.GetString("genel_baslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   HABERLER benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string haberler {
            get {
                return ResourceManager.GetString("haberler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   KAYDOL benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string kaydol {
            get {
                return ResourceManager.GetString("kaydol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BİTLİS&apos;İN TARİHİ TAŞ EVLERİNE ZİYARETÇİ AKINI OLUŞTU benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string kb1 {
            get {
                return ResourceManager.GetString("kb1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SPİL DAĞINDAN SONBAHAR MANZARALARI benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string kb2 {
            get {
                return ResourceManager.GetString("kb2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   YER ALTINDAKİ GİZEMLİ DÜNYA: KARACA MAĞARASI benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string kb3 {
            get {
                return ResourceManager.GetString("kb3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Devamı için tıklayınız. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ks {
            get {
                return ResourceManager.GetString("ks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bitlis&apos;in Hizan ilçesine bağlı Gayda köyünün yıllara meydan okuyan taş evleri, sonbahar birlikte ziyaretçilerini ağırlıyor. 
        ///              Çoğu, derin vadiler arasındaki yamaçlara kurulu çok katlı tarihi taş evlerden oluşan köyler, 
        ///              sonbaharda fotoğraf sanatçıları, gezginler ve turistlerden büyük ilgi görüyor. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ky1 {
            get {
                return ResourceManager.GetString("ky1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Manisa&apos;da, endemik bitkileri ve yılkı atları ile ilgi çeken, 1517 rakımdaki Spil Dağı Milli Parkı&apos;nda sonbahar güzelliği yaşanıyor. 
        ///              Orman manzarası, havadan dronla görüntülendi. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ky2 {
            get {
                return ResourceManager.GetString("ky2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gümüşhane&apos;de dünyanın sayılı damla taş mağaralarından olan, 150 milyon yıllık olduğu belirtilen Karaca Mağarası, 
        ///                yaz turizm sezonunda 90 bin ziyaretçiyi ağırladı. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ky3 {
            get {
                return ResourceManager.GetString("ky3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MARDİN  benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string mardin {
            get {
                return ResourceManager.GetString("mardin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mardin ile İlgili Efsaneler benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string mardin_efsane {
            get {
                return ResourceManager.GetString("mardin_efsane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   GENEL benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string mardin_genel {
            get {
                return ResourceManager.GetString("mardin_genel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   GEZİLECEK YERLER benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string mardin_gezilecekyer {
            get {
                return ResourceManager.GetString("mardin_gezilecekyer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TARİHİ benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string mardin_tarihi {
            get {
                return ResourceManager.GetString("mardin_tarihi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   YÖREYE ÖZGÜ YEMEKLER benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string mardin_yemek {
            get {
                return ResourceManager.GetString("mardin_yemek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Merhaba benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string merhaba {
            get {
                return ResourceManager.GetString("merhaba", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OTURUM AÇ benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string oturumac {
            get {
                return ResourceManager.GetString("oturumac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OTURUMU KAPAT benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string oturumukapat {
            get {
                return ResourceManager.GetString("oturumukapat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Seyahat etmekten hoşlanır mısınız? Tabii ki dediğinizi duyar gibiyim.  benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string s1 {
            get {
                return ResourceManager.GetString("s1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Seyahat etmek yeni yerler görmek, yeni insanlar tanımak, farklı lezzetleri tatmak ve şehrin, 
        ///        gezdiğimiz yerin havasını tüm bedenimizde hissetmektir. Tarifsiz bir mutluluk verir. 
        ///        Hele bir de seyahat esnasında her şey planladığınız gibi gitmişse o zaman değmeyin keyfimize.  benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string s2 {
            get {
                return ResourceManager.GetString("s2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bir seyahate başlamadan önce gideceğimiz yeri iyi tespit etmek gerekir.  
        ///        Zorunlu bir seyahat değilse (iş, okul, sağlık) öncelikle gideceğiniz yer hakkında bir ön araştırma yapmalısınız.
        ///        Gideceğiniz yeri belirledikten sonra o yer hakkında bilgi edinmelisiniz. İşte ben ve sitem sizin için buradayız. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string s3 {
            get {
                return ResourceManager.GetString("s3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BİZE ULAŞIN benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string s4 {
            get {
                return ResourceManager.GetString("s4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ŞANLIURFA benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string sanliurfa {
            get {
                return ResourceManager.GetString("sanliurfa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Şanlıurfa ile İlgili Efsaneler benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string sanliurfa_efsane {
            get {
                return ResourceManager.GetString("sanliurfa_efsane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ŞEHİRLER benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string sehirler {
            get {
                return ResourceManager.GetString("sehirler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mardin ili Güneydoğu Anadolu Bölgesi&apos;nin Dicle Bölümü&apos;nde yer alır.
        ///                    Suriye ile sınır komşusudur. Güneyinde Suriye, batısında Şanlıurfa ili, kuzeyinde Diyarbakır ve Batman illeri,
        ///                    kuzeydoğusunda Siirt ili ve doğusunda Şırnak ili bulunur. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string y1 {
            get {
                return ResourceManager.GetString("y1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mardin, Yukarı Mezopotamya havzasında Dicle ve Fırat nehirleri arasında aynı adı taşıyan ilde yer almaktadır.
        ///                    Bu bölge eski Yunanlılar tarafından “iki nehir arasındaki ülke” olarak adlandırılıyordu. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string y2 {
            get {
                return ResourceManager.GetString("y2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tahılların ana depolarından biri olarak kabul edilir. Zengin toprağı nedeniyle birçok uygarlığın doğum yeri olmuştur.
        ///                    Tarım ve hayvancılık bu havzada başlamış ve en eski efsaneler buradan çıkmıştır. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string y3 {
            get {
                return ResourceManager.GetString("y3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Nuh Tufanı, Peygamber İdris (İncil&apos;de Enoch olarak bilinir) ve daha birçok efsane bu topraklara atfedilir. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string y4 {
            get {
                return ResourceManager.GetString("y4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1960&apos;lı bakış açısına göre başlangıç ​ve kır planı olarak başlamaya başladı.
        ///                    1990 yılındaki dört ilçenin komşu illere nüfusu %14,4 oranındadır. 2000 nüfusta ilk defa kır kırsalı,
        ///                    kent gerisinde kalanlar. Bunda en önemli saygılar ve 90&apos;lı karşılaşmalarla ilgili etkinliklerdir.
        ///                    Güvenlik kaygıları nedeniyle hem ildeki kesimlerden, hem de diğer illerden Mardin şehrine taşınma hareketlerine başladı. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string y5 {
            get {
                return ResourceManager.GetString("y5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Şehir nüfusu oranı %60, kırsal nüfus oranı %43&apos;tür. Nüfusu en yüksek ilçeler sırasıyla Kızıltepe, Merkez, Nusaybin ve Midyat&apos;tır.
        ///                    Genç bir nüfus yapısına sahiptir. 2000 yılına göre 15 yaşın altındaki nüfusun oranı %44,8&apos;dir. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string y6 {
            get {
                return ResourceManager.GetString("y6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Türkiye&apos;deki en farklılaşmış nüfusa sahip illerinden biridir.
        ///                    İlde Kürtler, Hıristiyan Süryaniler, Sünni Araplar, Türkler, Yezidiler ve Ermeniler yaşamaktadır.
        ///                    Zaman içinde Süryani ve Yezidi nüfusu göçler sebebiyle azalmıştır.
        ///                    Lübnan&apos;ın başkenti Beyrut&apos;ta Mardin ve Midyat bölgesinde az sayıda Süryani yaşamaktadır. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string y7 {
            get {
                return ResourceManager.GetString("y7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mardin, yazları çok sıcak ve kurak, kışları ise soğuk,
        ///                    yağışlı ve ara sıra karlı geçen sıcak yaz Akdeniz iklimine (Köppen: Csa, Trewartha: Cs) sahiptir.
        ///                    Mardin çok güneşli, yılda 3000 saatin üzerinde güneş alıyor.
        ///                    Yazın sıcaklıklar kolayca 40 °C&apos;ye (104 °F) ulaşabilirken, karasal doğası nedeniyle kış havası Aralık ve Mart ayları arasında
        ///                    hala biraz yaygındır ve genellikle bir veya iki hafta kar yağar. Kaydedilen en yüksek sı [dizenin kalan bölümü kesildi]&quot;; benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string y8 {
            get {
                return ResourceManager.GetString("y8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   YORUMLAR benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string yorum {
            get {
                return ResourceManager.GetString("yorum", resourceCulture);
            }
        }
    }
}
